### PR TITLE
adding new failing tests for nested shared instances

### PR DESCRIPTION
**Pull request by daniel-meister**
Unfortunately, 6eca710 does not seem to solve the problem; it's only hiding it one layer deeper; I'll start thinking about a better solution in the morning.
So far this is simply to illustrate the problem; feel free to reject this PR.

### CODE REVIEW

**Comment by TomBZombie** [comment]
I don't have time to test this tonight but is it going to be as simple as keeping a copy of the original $args?

```php
return function($args, $share = []) use ($paramInfo, $rule) {
			if ($rule->shareInstances) $share = array_merge($share, array_map([$this, 'create'], $rule->shareInstances));	
			if ($share || $rule->constructParams) $mergedArgs = array_merge($args, $this->expand($rule->constructParams, $share), $share);
			$parameters = [];
			
			foreach ($paramInfo as list($class, $allowsNull, $sub, $new)) {
				if ($args) for ($i = 0; $i < count($args); $i++) {
					if ($class && $mergedArgs[$i] instanceof $class || ($mergedArgs[$i] === null && $allowsNull)) {
						$parameters[] = array_splice($mergedArgs, $i, 1)[0];
						continue 2;
					}
				}
				if ($class) $parameters[] = $sub ? $this->expand($rule->substitutions[$class], $share) : $this->create($class, $args, $new, $share);
				else if ($mergedArgs) $parameters[] = $this->expand(array_shift($mergedArgs));
			}
			return $parameters;
		};

```

**Comment by daniel-meister** [comment]
Yes, this was absolutely the correct idea. In addition, I had to fix the object creation cache though to fix another test case that was relying on the previous behaviour.

Maybe we should also think a bit more about the side effects of `array_splice` and `array_shift` that are now applied to the temporary copy only.

**Comment by TomBZombie** [comment]
It's a good question but now it's a temporary copy is array splice/shift an issue? The alternative is keeping an index number that stores the next element in $args that needs to be assigned.

**Comment by daniel-meister** [comment]
Yes, but (at least for me) behaviour was more obvious when the args got "consumed" i.e. from

```php

class A {
    public $b;
    public $str;
    public function __construct(B $b, $str) {
        $this->b = $b;
        $this->str = $str;
    }
}

class B {
    public $str;
    public function __construct($str) {
        $this->str = $str;
    }
}

$dice = new Dice\Dice;
$rule = new Dice\Rule;
$rule->constructParams[] = ['B'];
$dice->addRule('B',$rule);
$a = $dice->create('A,['A']);

echo $a->b->str;
```
I would expect output `B` (of course this can be debated) but at the moment it will give `A` as the argument was not "consumed" but passed down the graph.

**Comment by garrettw** [comment]
Interesting. Didn't realize what this was all about until that last example. I would expect the output to be `'B'` as well, assuming I were to insert the missing `'` after `$dice->create('A` :smile:

**Pull request merged**
